#!/bin/bash

echo "Warning: this will add a '~/bin/git-changelog' executable "
echo " <Press a key to continue or quit with Ctrl-C> "
read ans

mkdir -p ~/bin
cp -v git-changelog ~/bin
test -e ~/.git-changelog.rc || cp -v git-changelog.rc ~/.git-changelog.rc

chmod +x ~/bin/git-changelog -v

echo
echo "NOTE: You should make sure that your ~/bin is in your \$PATH"


